#=========================== Filebeat inputs =============================
filebeat.inputs:
- type: log 
  enabled: true
  paths:
    - C:/Users/youssra/Desktop/DATA/Firewall_log.csv


#----------------------------- Logstash output --------------------------------
output.logstash:
  hosts: ["localhost:5044"]